module.exports = {
  USER_CONNECTED: "USER_CONNECTED",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  VERIFY_USER: "VERIFY_USER",
  STARTING_GAME: "STARTING_GAME",
  CHOOSED_ITEM: "CHOOSED_ITEM",
  RESULT: "RESULT",
  TIMER: "TIMER"
};
